### ISSUE TITLE
Inline Images in PDF?

### ISSUE THREAD

**Issue by seljuck** [minvws/nl-rdo-zammad-api-export#205]
Hello,

Does the export also pull inline images into the PDF document?

Thanks

**Comment by ricklambrechts** [comment]
I currently do not know what happens with inline images. I know the attachments are exported. 

I can try it out.

**Comment by seljuck** [comment]
Thank you for checking for me.

Do the attachments become part of the PDF? If so, what happens with unknown mime types, like an Autocad Drawing?

**Comment by ricklambrechts** [comment]
I checked it but sadly we are not generating PDF's currently. That is wrong in our Readme. We generate a readable HTML file for each ticket and also export the ticket, tags, history and articles in seperated json files. 

Further, I have tested the inline attachments and discoverred that the inline attachments are not propertly shown. This is because we currently do not change the body of each article so the internal attachment link is in the body. We already downloaded the attachments but the inline image is not shown. [I have already created a PR to show the inline image](https://github.com/minvws/nl-rdo-zammad-api-export/pull/207).

**Comment by seljuck** [comment]
Thank you again for working on these issues.

The PDF aspect is not a big problem. I can use Project Gotonberg to do that https://gotenberg.dev/

The other attachments being separate is also good for my particular setup.

**Comment by ricklambrechts** [comment]
The inline images are now working. Can we close the issue?

**Comment by seljuck** [comment]
Thank you for updating the project for this request. Much appreciated!
